// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSYuPbK-P0h6FYnHk68cPdffIAbQcOwBo',
    appId: '1:67171818680:web:91f30b8331dafa78cfe84d',
    messagingSenderId: '67171818680',
    projectId: 'cogent-cocoa-378019',
    authDomain: 'cogent-cocoa-378019.firebaseapp.com',
    databaseURL: 'https://cogent-cocoa-378019-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cogent-cocoa-378019.appspot.com',
    measurementId: 'G-TF26TRFMVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgBWKb9LdDpMpQdbGe4vKaZn3TZv3euRA',
    appId: '1:67171818680:android:6697b067c4d3a3c3cfe84d',
    messagingSenderId: '67171818680',
    projectId: 'cogent-cocoa-378019',
    databaseURL: 'https://cogent-cocoa-378019-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cogent-cocoa-378019.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9vN7Mq2Gb4-JXFNW1-aplLU7S4WmxThk',
    appId: '1:67171818680:ios:f8de13e66d897cf7cfe84d',
    messagingSenderId: '67171818680',
    projectId: 'cogent-cocoa-378019',
    databaseURL: 'https://cogent-cocoa-378019-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cogent-cocoa-378019.appspot.com',
    iosBundleId: 'com.example.iotBtl',
  );
}
