// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2CFfJ6JPILTawiXko91IUTSfZKvU2080',
    appId: '1:378923159186:android:f17d2323a90a11a147a04b',
    messagingSenderId: '378923159186',
    projectId: 'btl-iot-27a9c',
    databaseURL: 'https://btl-iot-27a9c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'btl-iot-27a9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXLP4Szf71k8YKxfBC6vwGGz799VcIQ4M',
    appId: '1:378923159186:ios:7bb24d429cc0b9c147a04b',
    messagingSenderId: '378923159186',
    projectId: 'btl-iot-27a9c',
    databaseURL: 'https://btl-iot-27a9c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'btl-iot-27a9c.appspot.com',
    iosBundleId: 'com.example.appIotBtl',
  );
}
